dist: trusty
language: python
python:
  - "3.6"

sudo: required

cache:
  directories:
    - $HOME/.cache/pip
    - /home/travis/.sonar/cache

services:
- docker

install:
- make install

script:
- make lint
- make test

after_success:
- coveralls
- bash scripts/docker_build_and_push.sh

notifications:
  email:
    on_success: change
    on_failure: change

